name: nccl (dev)

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      fork_repo:
        description: 'Fork repository (e.g., tokk-nv/jetson-containers)'
        required: false
        type: string
      fork_branch:
        description: 'Branch from fork to test (e.g., dev)'
        required: false
        type: string
        default: 'dev'

jobs:
  test-package-orin:
    runs-on: [self-hosted, linux, arm64, jetson, orin]
    name: "Package Build Test (orin)"

    steps:
      - name: Pre-checkout cleanup
        run: ./.github/scripts/pre-checkout-cleanup.sh

      - name: Checkout PR or Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event_name == 'workflow_dispatch' && inputs.fork_repo != '' && inputs.fork_repo || github.repository }}
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.fork_branch != '' && inputs.fork_branch || github.ref }}

      - name: Display system info
        run: ./.github/scripts/system-info.sh

      - name: Record environment variables
        run: ./.github/scripts/env-info.sh

      - name: Clean environment for fresh build
        run: ./.github/scripts/clean-environment.sh

      - name: Show git repository state
        run: ./.github/scripts/git-status.sh

      - name: Test build nccl package on orin
        id: package-test
        run: ./.github/scripts/build-package.sh nccl

      - name: Analyze build results
        if: always()
        run: ./.github/scripts/analyze-results.sh nccl ${{ steps.package-test.outputs.stage1 }} ${{ steps.package-test.outputs.stage2 }} ${{ steps.package-test.outputs.build_status }}

      - name: Test build results
        run: ./.github/scripts/test-results-summary.sh nccl ${{ steps.package-test.outputs.stage1 }} ${{ steps.package-test.outputs.stage2 }} ${{ steps.package-test.outputs.build_status }} ${{ steps.package-test.outputs.failure_phase }} ${{ steps.package-test.outputs.failure_stage }} ${{ steps.package-test.outputs.failure_component }}
