name: PR Test - vllm (Thor)

on:
  # Disabled - no Thor runner available
  # pull_request:
  #   types: [opened, synchronize, reopened]
  #   branches: [ dev ]
  workflow_dispatch:
    inputs:
      fork_repo:
        description: 'Fork repository (e.g., tokk-nv/jetson-containers)'
        required: false
        type: string
      fork_branch:
        description: 'Branch from fork to test (e.g., dev)'
        required: false
        type: string
        default: 'dev'

jobs:
  test-vllm-thor:
    runs-on: [self-hosted, linux, arm64, jetson-thor]
    name: "vllm Package Test (Thor)"

    steps:
      - name: Checkout PR or Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event_name == 'workflow_dispatch' && inputs.fork_repo != '' && inputs.fork_repo || github.repository }}
          ref: ${{ github.event_name == 'workflow_dispatch' && inputs.fork_branch != '' && inputs.fork_branch || github.ref }}

      - name: Display system info
        run: |
          echo "=== Jetson Thor System Info ==="
          echo "Hello from $HOSTNAME running on Jetson Thor!"
          uname -a
          nvidia-smi || echo "No nvidia-smi (Jetson usually)"
          echo "GPU Memory:"
          cat /proc/device-tree/compatible || echo "Device tree info not available"

      - name: Show git repository state
        run: |
          echo "=== Git Status ==="
          git status
          echo ""
          echo "=== Recent Git History (last 10 commits) ==="
          git log --oneline -10

      - name: Test vllm package on Thor
        run: |
          echo "=== Testing vllm package on Jetson Thor ==="
          chmod +x ./build.sh
          echo "Listing available packages..."
          ./build.sh --list-packages
          echo ""
          echo "Testing vllm package specifically..."
          ./build.sh --build-flags="--no-cache" --no-github-api vllm
          echo "✅ vllm package test completed successfully on Thor!"

      - name: Test results
        run: |
          echo "=== vllm Test Results ==="
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "PR from: ${{ github.event.pull_request.head.repo.full_name }}"
            echo "Branch: ${{ github.head_ref }}"
            echo "Commit: ${{ github.event.pull_request.head.sha }}"
          else
            echo "Manual run from: ${{ github.repository }}"
            echo "Branch: ${{ github.ref_name }}"
            echo "Commit: ${{ github.sha }}"
          fi
          echo ""
          echo "✅ vllm package: PASSED on Jetson Thor"
          echo "Hardware: Jetson Thor"
          echo "Package: vllm"
          echo "Status: SUCCESS"
